Repository blockeraai/blockera, pull requests merged in 2024-09, with the labels that each got.

#161 Improvements, and Complete Blockera repository CI/CD workflows
  .github/build-plugin-zip/action.yml
  .github/setup-php/action.yml
  .github/workflows/build-plugin-zip-tests.yml
  .github/workflows/build-plugin-zip.yml
  .github/workflows/bundle-size.yml
  .github/workflows/code-lint.yml
  .github/workflows/cypress-components-tests.yml
  .github/workflows/cypress-e2e-tests.yml
  .github/workflows/jest-unit-tests.yml
  .github/workflows/php-unit-tests.yml
  .github/workflows/plugin-check.yml
  .github/workflows/upload-release-to-plugin-repo.yml
  .github/workflows/virus-total.yml
  .gitignore
  assets/css/dynamic-styles.css
  bin/build-plugin-zip.sh
  bin/generate-build-plugin-zip-sh.php
  bin/generate-readme-txt.php
  bin/get-plugin-info.php
  bin/plugin-helpers.php
  bin/update-cypress-env-specs.sh
  cypress.config.js
  cypress.env-example.json
  docs/contributors/bin/generate-build-plugin-zip-sh.md
  package.json
  packages/blockera-admin/js/test/blockera-block-manager.panels.build.e2e.cy.js
  packages/blockera/js/test/blockera-editor.build.e2e.cy.js
  packages/blockera/package.json
  packages/dev-cypress/js/support/e2e.js
  packages/editor/js/extensions/libs/background/test/background-color.build.e2e.cy.js
  packages/wordpress/php/Assets/css/dynamic-styles.css
  packages/wordpress/php/AssetsLoader.php
Labels: documentation, enhancement

#175 Feat: Spacer block support
  packages/blocks/core/CHANGELOG.md
  packages/blocks/core/js/wordpress-blocks-list.json
  packages/blocks/core/js/wordpress/index.js
  packages/blocks/core/js/wordpress/spacer/index.js
  packages/blocks/core/js/wordpress/spacer/test/block.inner-blocks.e2e.cy.js
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/size/compatibility/height.js
  packages/editor/js/extensions/libs/size/test/height.compatibility.e2e.cy.js
Labels: enhancement

#172 fix: input control does not accepts 0 value
  packages/controls/CHANGELOG.md
  packages/controls/js/libs/input-control/components/unit-input.js
  packages/controls/js/libs/input-control/index.js
  packages/controls/js/libs/input-control/test/input-control.cy.js
Labels: bug

#174 fix: style issue when the selected block is unsupported
  .github/workflows/build-plugin-zip.yml
  assets/css/dynamic-styles.css
  bin/plugin/commands/test/__snapshots__/changelog.spec.js.snap
  bin/plugin/commands/test/changelog.spec.js
  packages/blockera/js/index.js
  packages/blockera/php/Providers/AppServiceProvider.php
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/components/block-base.js
  packages/editor/js/extensions/hooks/block-settings.js
  packages/editor/js/extensions/libs/background/test/background-color.build.e2e.cy.js
  packages/editor/js/extensions/libs/background/test/background-color.e2e.cy.js
  packages/editor/js/extensions/libs/effects/test/backdrop-filters.e2e.cy.js
  packages/editor/js/extensions/libs/effects/test/filters.e2e.cy.js
  packages/editor/js/extensions/libs/effects/test/transforms.e2e.cy.js
  packages/editor/js/extensions/libs/layout/test/gap.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/height.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/max-height.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/max-width.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/min-height.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/min-width.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/width.e2e.cy.js
  packages/editor/js/extensions/libs/spacing/test/spacing.e2e.cy.js
  packages/editor/js/extensions/libs/typography/test/font-color.e2e.cy.js
  packages/editor/js/extensions/libs/typography/test/font-size.e2e.cy.js
  packages/editor/js/hooks/use-attributes/index.js
  packages/editor/js/style-engine/hooks/use-computed-css-props.js
  packages/editor/js/style-engine/test/style-engine.e2e.cy.js
  packages/editor/php/StyleDefinitions/BaseStyleDefinition.php
  packages/editor/php/StyleDefinitions/Layout.php
  packages/editor/php/StyleEngine.php
  packages/editor/php/helpers.php
  packages/editor/php/tests/Fixtures/StyleEngine/block-state-selectors.php
  packages/editor/php/tests/Fixtures/StyleEngine/calculation-css-selector.php
  packages/editor/php/tests/Fixtures/StyleEngine/inner-block-state-selectors.php
  packages/editor/php/tests/TestHelpers.php
  packages/utils/CHANGELOG.md
  packages/utils/php/Utils.php
  packages/utils/php/tests/TestUtils.php
  packages/wordpress/CHANGELOG.md
  packages/wordpress/php/AssetsLoader.php
  packages/wordpress/php/RenderBlock/Parser.php
  packages/wordpress/php/RenderBlock/Render.php
  packages/wordpress/php/RenderBlock/SavePost.php
  packages/wordpress/php/functions.php
  packages/wordpress/php/tests/TestFunctions.php
Labels: bug, documentation, enhancement
