Repository blockeraai/blockera, pull requests merged in 2025-05, with the labels that each got.

#323 Feat: Block Card v3 - Style Variations
  packages/controls/js/libs/button/style.scss
  packages/controls/js/libs/popover/types/types.js
  packages/controls/js/libs/style.scss
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/components/test/block-partials.e2e.cy.js
  packages/editor/js/extensions/libs/base/config/index.js
  packages/editor/js/extensions/libs/base/config/style-variations.js
  packages/editor/js/extensions/libs/block-card/block-states/test/block-states-inner-blocks.general-2.e2e.cy.js
  packages/editor/js/extensions/libs/block-card/block-states/test/block-states.general-2.e2e.cy.js
  packages/editor/js/extensions/libs/block-card/components/block-card.js
  packages/editor/js/extensions/libs/block-card/components/block-card.scss
  packages/editor/js/extensions/libs/block-card/inner-blocks/test/inner-blocks-extension.inner-blocks.e2e.cy.js
  packages/editor/js/extensions/libs/block-card/style-variations/components/block-styles.js
  packages/editor/js/extensions/libs/block-card/style-variations/components/block-styles.scss
  packages/editor/js/extensions/libs/block-card/style-variations/components/inserter-preview-panel.js
  packages/editor/js/extensions/libs/block-card/style-variations/components/preview-panel.js
  packages/editor/js/extensions/libs/block-card/style-variations/index.js
  packages/editor/js/extensions/libs/block-card/style-variations/style.scss
  packages/editor/js/extensions/libs/block-card/style-variations/test/style-variations.e2e.cy.js
  packages/editor/js/extensions/libs/block-card/style-variations/utils.js
  packages/editor/js/extensions/libs/block-card/style.scss
  packages/editor/js/extensions/libs/index.js
  packages/editor/js/extensions/libs/shared/index.js
  packages/editor/js/extensions/libs/style-variations/extension.js
  packages/editor/js/extensions/libs/style-variations/index.js
  packages/editor/js/extensions/libs/style-variations/style.scss
  packages/editor/js/extensions/libs/style-variations/types/index.js
  packages/editor/js/extensions/libs/style.scss
  packages/icons/js/library-ui/icons/extension-inner-blocks.svg
  packages/icons/js/library-ui/icons/extension-style-variations.svg
  packages/icons/js/library-ui/icons/index.js
  packages/icons/js/library-ui/icons/more-vertical-small.svg
  packages/icons/js/library-ui/icons/style-variations.svg
Labels: Enhancement

#326 Refactor: `wp-env` configs and local development!
  .env.example
  .github/scripts/setup-wp-env.js
  .github/workflows/build-plugin-zip-tests.yml
  .github/workflows/cypress-e2e-tests.yml
  .github/workflows/cypress-visual-tests.yml
  .github/workflows/php-unit-tests.yml
  .github/wp-env-configs/base.json
  .github/wp-env-configs/blocksy.json
  .github/wp-env-configs/development.json
  .github/wp-env-configs/plugins.json
  .github/wp-env-configs/telemetry.json
  .github/wp-env-configs/woocommerce.json
  package.json
  packages/blockera/CHANGELOG.md
Labels: Enhancement

#328 Feat: Implements a extension for provide extra options for specific block states
  packages/blockera/php/functions.php
  packages/blockera/php/tests/FunctionsTest.php
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/background/styles.js
  packages/editor/js/extensions/libs/base/config/block-states.js
  packages/editor/js/extensions/libs/base/config/index.js
  packages/editor/js/extensions/libs/block-card/block-states/extension.js
  packages/editor/js/extensions/libs/block-card/block-states/index.js
  packages/editor/js/extensions/libs/block-card/block-states/states.js
  packages/editor/js/extensions/libs/block-card/block-states/style.js
  packages/editor/js/extensions/libs/block-card/block-states/types/index.js
  packages/editor/js/extensions/libs/effects/styles.js
  packages/editor/js/extensions/libs/flex-child/styles.js
  packages/editor/js/extensions/libs/layout/styles.js
  packages/editor/js/extensions/libs/mouse/styles.js
  packages/editor/js/extensions/libs/position/styles.js
  packages/editor/js/extensions/libs/shared/index.js
  packages/editor/js/extensions/libs/size/styles.js
  packages/editor/js/extensions/libs/spacing/styles.js
  packages/editor/js/extensions/libs/typography/styles.js
  packages/editor/js/hooks/use-attributes/helpers.js
  packages/editor/js/hooks/use-attributes/reducer.js
  packages/editor/js/hooks/use-editor-store/index.js
  packages/editor/js/schemas/block-supports/state-block-supports-list.json
  packages/editor/js/style-engine/components/state-style.js
  packages/editor/js/style-engine/get-computed-css-props.js
  packages/editor/js/style-engine/test/computed-css-declarations.spec.js
  packages/editor/php/StyleDefinitions/BaseStyleDefinition.php
  packages/editor/php/StyleEngine.php
  packages/editor/php/helpers.php
Labels: Enhancement

#331 fix: reported bugs from users
  .gitignore
  packages/controls/CHANGELOG.md
  packages/controls/js/libs/color-picker-control/components/color-pallet.scss
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/block-card/block-states/states.js
  packages/editor/js/extensions/libs/block-card/block-states/style.scss
  packages/editor/js/extensions/libs/block-card/inner-blocks/components/item-header.js
  packages/editor/js/extensions/libs/block-composite/components/categorized-items.js
  packages/editor/php/StyleDefinitions/BaseStyleDefinition.php
  packages/editor/php/StyleDefinitions/Traits/WithDisplayValueTrait.php
Labels: Bug

#333 Feat: Style variations live preview
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/block-card/style-variations/components/block-styles.js
  packages/editor/js/extensions/libs/block-card/style-variations/components/block-styles.scss
  packages/editor/js/extensions/libs/block-card/style-variations/components/preview-panel.js
  packages/editor/js/extensions/libs/block-card/style-variations/index.js
Labels: Enhancement

#332 feat: Style engine v2 check and improvements
  .github/setup-php/action.yml
  config/app.php
  packages/blockera/php/tests/FunctionsTest.php
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/shared/index.js
  packages/editor/js/extensions/libs/spacing/compatibility/spacing.js
  packages/editor/js/hooks/use-attributes/helpers.js
  packages/editor/js/hooks/use-attributes/reducer.js
  packages/editor/js/style-engine/get-compatible-block-css-selector.js
  packages/editor/php/Providers/StyleDefinitionsProvider.php
  packages/editor/php/StyleDefinitions/Flex.php
  packages/editor/php/StyleEngine.php
Labels: Bug, Enhancement

#338 fix: did not properly show while selecting unsupported blocks
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/hooks/block-settings.js
  packages/editor/js/extensions/libs/base/config/layout.js
  packages/editor/js/extensions/libs/layout/test/flex-wrap.compatibility.e2e.cy.js
  packages/editor/js/extensions/libs/layout/test/flex-wrap.e2e.cy.js
  packages/editor/js/hooks/index.js
  packages/editor/js/hooks/use-block-side-effects/apply.js
  packages/editor/js/hooks/use-block-side-effects/classes.js
  packages/editor/js/hooks/use-block-side-effects/index.js
  packages/editor/js/hooks/use-block-side-effects/restore.js
Labels: Bug
