Repository blockeraai/blockera, pull requests merged in 2025-04, with the labels that each got.

#292 Feat: WP 6.8 Compatibility
  .github/workflows/cypress-e2e-tests.yml
  blockera.php
  bootstrap/callbacks.php
  bootstrap/hooks.php
  config/telemetry-rest-params.php
  config/telemetry.php
  packages/blockera/CHANGELOG.md
  packages/blockera/php/Providers/AppServiceProvider.php
  packages/blocks/core/CHANGELOG.md
  packages/blocks/core/js/wordpress/post-content/test/functionality.blocks-2.e2e.cy.js
  packages/blocks/core/js/wordpress/table/test/functionality.blocks-2.e2e.cy.js
  packages/blocks/core/test/customized-selector-blocks-cache.json
  packages/controls/CHANGELOG.md
  packages/controls/js/libs/angle-picker-control/style.scss
  packages/controls/js/libs/base-control/style.scss
  packages/controls/js/libs/border-control/index.js
  packages/controls/js/libs/border-control/style.scss
  packages/controls/js/libs/border-control/test/border-control.cy.js
  packages/controls/js/libs/border-radius-control/index.js
  packages/controls/js/libs/box-border-control/index.js
  packages/controls/js/libs/button/style.scss
  packages/controls/js/libs/color-picker-control/components/color-pallet.scss
  packages/controls/js/libs/feature-wrapper/style.scss
  packages/controls/js/libs/gradient-bar-control/style.scss
  packages/controls/js/libs/icon-control/style.scss
  packages/controls/js/libs/input-control/components/input.scss
  packages/controls/js/libs/input-control/components/unit-input.scss
  packages/controls/js/libs/input-control/test/utils.spec.js
  packages/controls/js/libs/input-control/utils.js
  packages/controls/js/libs/label-control/label-control-container.js
  packages/controls/js/libs/label-control/style.scss
  packages/controls/js/libs/layout-matrix-control/style.scss
  packages/controls/js/libs/mask-control/style.scss
  packages/controls/js/libs/media-image-control/style.scss
  packages/controls/js/libs/more-features/style.scss
  packages/controls/js/libs/position-button/index.js
  packages/controls/js/libs/range-control/index.js
  packages/controls/js/libs/range-control/style.scss
  packages/controls/js/libs/repeater-control/style.scss
  packages/controls/js/libs/select-control/index.js
  packages/controls/js/libs/select-control/style.scss
  packages/controls/js/libs/style.scss
  packages/controls/js/libs/tabs/style.scss
  packages/controls/js/libs/toggle-control/style.scss
  packages/controls/js/libs/toggle-select-control/index.js
  packages/controls/js/libs/toggle-select-control/style.scss
  packages/dev-cypress/CHANGELOG.md
  packages/dev-cypress/js/helpers/editor.js
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/base/config/border-and-shadow.js
  packages/editor/js/extensions/libs/base/config/effects.js
  packages/editor/js/extensions/libs/base/config/typography.js
  packages/editor/js/extensions/libs/settings/components/support-item.js
  packages/editor/js/extensions/libs/settings/index.js
  packages/editor/js/extensions/libs/settings/style.scss
  packages/telemetry/php/Jobs.php
  packages/wordpress/CHANGELOG.md
  packages/wordpress/php/RenderBlock/Setup.php
  packages/wordpress/php/tests/RenderBlock/TestSetup.php
Labels: Enhancement

#293 Fix: add the bootstrap directory into archive file
  bin/build-plugin-zip.sh
  packages/blockera/CHANGELOG.md
  packages/blocks/core/CHANGELOG.md
  packages/blocks/core/js/wordpress/column/test/functionality.build.e2e.cy.js
Labels: Bug, Enhancement

#295 Feat: Check WP 6.8-RC4 Compatibility
  blockera.php
  packages/blocks/core/CHANGELOG.md
  packages/blocks/core/js/third-party/blocksy-breadcrumbs/test/breadcrumbs-block.blocksy.e2e.cy.js
  packages/blocks/core/js/woocommerce-blocks-list.json
  packages/blocks/core/js/wordpress-blocks-list.json
  packages/blocks/core/js/wordpress/index.js
  packages/blocks/core/js/wordpress/query-total/index.js
  packages/blocks/core/js/wordpress/query-total/test/functionality.blocks-2.e2e.cy.js
  packages/blocks/core/js/wordpress/query-total/test/test-content.js
  packages/blocks/core/test/blocks-list-monitoring.woocommerce.e2e.cy.js
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/block-card/components/block-card.js
  packages/editor/js/extensions/libs/block-card/test/block-card.e2e.cy.js
  packages/editor/js/extensions/libs/block-card/test/sticky-block-card.e2e.cy.js
  packages/wordpress/CHANGELOG.md
  packages/wordpress/php/RenderBlock/V1/Render.php
  packages/wordpress/php/RenderBlock/V2/RenderContent.php
Labels: Enhancement

#294 Feat: UI improvements on Admin Pannel
  packages/blockera-admin/js/dashboard.js
  packages/blockera-admin/js/style.scss
  packages/controls/js/libs/button/types/index.js
  packages/controls/js/libs/flex/index.js
  packages/controls/js/libs/flex/types/index.js
  packages/controls/js/libs/index.js
  packages/controls/js/libs/promotion-popover/components/promoter.js
  packages/controls/js/libs/promotion-popover/components/promotion-popover.js
  packages/controls/js/libs/promotion-popover/index.js
  packages/controls/js/libs/promotion-popover/style.scss
  packages/wordpress/CHANGELOG.md
  packages/wordpress/js/admin/components/header/style.scss
  packages/wordpress/js/admin/components/sidebar/style.scss
  packages/wordpress/js/admin/components/tabs/style.scss
  packages/wordpress/js/admin/style.scss
  visual-screenshots/baseline/blockera-dashboard.visual.cy-dashboard.png
Labels: Enhancement

#296 Feat: Inline Block Renaming from the Block Card
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/components/block-fill-partials.js
  packages/editor/js/extensions/components/test/block-partials.e2e.cy.js
  packages/editor/js/extensions/libs/block-card/components/block-card.js
  packages/editor/js/extensions/libs/block-card/components/block-card.scss
  packages/editor/js/extensions/libs/block-card/components/editable-block-name.js
  packages/editor/js/extensions/libs/block-card/test/block-card.e2e.cy.js
Labels: Enhancement

#297 Fix: Flex layout bug on breakpoints
  packages/editor/CHANGELOG.md
  packages/editor/php/StyleDefinitions/Layout.php
Labels: Bug

#298 Feat: implements the Custom CSS feature
  package-lock.json
  package.json
  packages/controls/CHANGELOG.md
  packages/controls/js/libs/code-control/index.js
  packages/controls/js/libs/code-control/style.scss
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/components/block-base.js
  packages/editor/js/extensions/libs/custom-style/extension.js
  packages/editor/js/extensions/libs/custom-style/test/custom-css.e2e.cy.js
  packages/editor/js/style-engine/components/block-style.js
  packages/editor/js/style-engine/components/types/index.js
  packages/wordpress/php/RenderBlock/V1/Render.php
  packages/wordpress/php/RenderBlock/V2/Transpiler.php
Labels: Enhancement

#300 feat: Improve Code Control
  package-lock.json
  package.json
  packages/controls/js/libs/code-control/index.js
  packages/controls/package.json
  visual-screenshots/baseline/blockera-dashboard.visual.cy-dashboard.png
Labels: Enhancement

#303 Fix: Double preview button in translated languages
  packages/controls/js/libs/code-control/index.js
  packages/controls/js/libs/code-control/style.scss
  packages/editor/CHANGELOG.md
  packages/editor/js/canvas-editor/bootstrap.js
  packages/editor/js/canvas-editor/components/preview.js
  packages/editor/js/canvas-editor/helpers.js
  packages/editor/js/canvas-editor/index.js
  packages/editor/js/canvas-editor/style.scss
  packages/editor/js/canvas-editor/test/get-targets.spec.js
  packages/editor/js/canvas-editor/types/index.js
  packages/editor/js/extensions/libs/size/components/aspect-ratio.js
  packages/editor/js/extensions/libs/size/test/aspect-ratio.compatibility.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/aspect-ratio.e2e.cy.js
Labels: Bug

#314 Fix: Design fix and improvements
  packages/blocks/core/CHANGELOG.md
  packages/blocks/core/js/wordpress/latest-comments/test/functionality.blocks-2.e2e.cy.js
  packages/blocks/core/js/wordpress/rss/test/functionality.blocks-2.e2e.cy.js
  packages/controls/CHANGELOG.md
  packages/controls/js/libs/feature-wrapper/index.js
  packages/controls/js/libs/feature-wrapper/style.scss
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/style-variations/components/block-styles.scss
Labels: Bug

#315 Feat: Extend the blockera block states
  .patch/paragraph-block-unsaved-data.php
  config/states.php
  package.json
  packages/blockera/CHANGELOG.md
  packages/blockera/php/Blockera.php
  packages/blockera/php/Providers/EditorAssetsProvider.php
  packages/blocks/core/CHANGELOG.md
  packages/blocks/core/js/third-party/blocksy-search/test/search-block.blocksy.e2e.cy.js
  packages/controls/CHANGELOG.md
  packages/controls/js/libs/feature-wrapper/index.js
  packages/controls/js/libs/feature-wrapper/style.scss
  packages/editor/CHANGELOG.md
  packages/editor/js/components/editor-advanced-label/selector.js
  packages/editor/js/extensions/index.js
  packages/editor/js/extensions/libs/block-card/components/breadcrumb.js
  packages/editor/js/extensions/libs/block-states/components/index.js
  packages/editor/js/extensions/libs/block-states/components/item-body.js
  packages/editor/js/extensions/libs/block-states/components/states-manager.js
  packages/editor/js/extensions/libs/block-states/helpers.js
  packages/editor/js/extensions/libs/block-states/index.js
  packages/editor/js/extensions/libs/block-states/test/default-breakpoints.spec.js
  packages/editor/js/extensions/libs/block-states/test/helpers.spec.js
  packages/editor/js/extensions/libs/block-states/test/states.js
  packages/editor/js/extensions/libs/block-states/types/state-types.js
  packages/editor/js/extensions/libs/index.js
  packages/editor/js/hooks/use-advanced-label-props/helpers.js
  packages/editor/js/index.js
  packages/editor/js/store/actions.js
  packages/editor/js/store/reducers.js
  packages/editor/js/store/selectors.js
  packages/editor/js/style-engine/components/state-style.js
  packages/utils/CHANGELOG.md
  packages/utils/js/object/index.js
  packages/utils/js/object/test/get-sorted-object.spec.js
Labels: Documentation, Enhancement

#320 Fix: Modal design issue
  packages/controls/js/libs/feature-wrapper/style.scss
  packages/controls/js/libs/modal/index.js
  packages/editor/CHANGELOG.md
Labels: Bug
