Repository blockeraai/blockera, pull requests merged in 2025-02, with the labels that each got.

#243 Fix: reported bugs from users
  packages/blocks/core/CHANGELOG.md
  packages/blocks/core/php/shared/attributes.php
  packages/dev-cypress/js/helpers/responsive.js
  packages/editor/CHANGELOG.md
  packages/editor/js/canvas-editor/bootstrap.js
  packages/editor/js/canvas-editor/index.js
  packages/editor/js/canvas-editor/intersection-observer-renderer.js
  packages/editor/js/canvas-editor/style.scss
  packages/editor/js/canvas-editor/test/canvas-editor.e2e.cy.js
  packages/editor/js/extensions/libs/layout/compatibility/flex-wrap.js
  packages/editor/js/extensions/libs/layout/extension.js
  packages/editor/js/extensions/libs/layout/styles.js
  packages/editor/js/extensions/libs/layout/test/flex-wrap.compatibility.e2e.cy.js
  packages/editor/js/extensions/libs/layout/test/flex-wrap.e2e.cy.js
  packages/editor/js/extensions/libs/layout/types/layout-props.js
  packages/editor/js/extensions/libs/size/compatibility/aspect-ratio.js
  packages/editor/js/extensions/libs/size/components/aspect-ratio.js
  packages/editor/js/extensions/libs/size/styles.js
  packages/editor/js/extensions/libs/size/test/aspect-ratio.compatibility.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/aspect-ratio.e2e.cy.js
  packages/editor/js/extensions/libs/size/test/aspect-ratio.spec.js
  packages/editor/php/StyleDefinitions/BaseStyleDefinition.php
  packages/editor/php/StyleDefinitions/Layout.php
  packages/editor/php/StyleDefinitions/Size.php
Labels: bug

#249 Performance Optimization
  packages/blockera/CHANGELOG.md
  packages/blockera/js/index.js
  packages/editor/CHANGELOG.md
  packages/editor/js/canvas-editor/bootstrap.js
  packages/editor/js/extensions/hooks/block-settings.js
  packages/editor/php/StyleDefinitions/BaseStyleDefinition.php
Labels: bug, enhancement

#251 feat: block-supports schemas
  .github/workflows/bundle-size.yml
  packages/editor/js/extensions/libs/border-and-shadow/css-generators/border-radius-generator.js
  packages/editor/js/extensions/libs/border-and-shadow/styles.js
  packages/editor/js/extensions/libs/types/StylesProps.js
  packages/editor/js/extensions/utils/index.js
  packages/editor/js/schemas/block-supports/background-block-supports-list.json
  packages/editor/js/schemas/block-supports/border-block-supports-list.json
  packages/editor/js/schemas/block-supports/box-shadow-block-supports-list.json
  packages/editor/js/schemas/block-supports/divider-block-supports-list.json
  packages/editor/js/schemas/block-supports/effects-block-supports-list.json
  packages/editor/js/schemas/block-supports/layout-block-supports-list.json
  packages/editor/js/schemas/block-supports/mouse-block-supports-list.json
  packages/editor/js/schemas/block-supports/outline-block-supports-list.json
  packages/editor/js/schemas/block-supports/position-block-supports-list.json
  packages/editor/js/schemas/block-supports/size-block-supports-list.json
  packages/editor/js/schemas/block-supports/spacing-block-supports-list.json
  packages/editor/js/schemas/block-supports/text-shadow-block-supports-list.json
  packages/editor/js/schemas/block-supports/typography-block-supports-list.json
  packages/editor/js/schemas/block.supports.schema.json
  packages/editor/js/style-engine/utils.js
  packages/editor/js/test/block-supports-list.spec.js
  packages/editor/php/StyleDefinitions/BaseStyleDefinition.php
  packages/editor/php/StyleDefinitions/Border.php
  packages/editor/php/helpers.php
Labels: enhancement

#252 Fix: Duplicate preview button
  packages/editor/CHANGELOG.md
  packages/editor/js/canvas-editor/helpers.js
  packages/editor/js/canvas-editor/test/get-targets.spec.js
  packages/telemetry/js/components/opt-in/opt-in.js
Labels: bug

#253 Feat: PR Playground configs
  .github-playground.json
  .github-pr-playground.example.json
  .github-pr-playground.json
  .github/workflows/create-demo-attachments.yml
  .github/workflows/remove-pr-config-files.yml
  packages/editor/CHANGELOG.md
Labels: enhancement

#254 Fix: Flex child block section not showing for 9 blocks
  packages/blocks/core/CHANGELOG.md
  packages/blocks/core/js/wordpress/buttons/test/block-attributes.blocks.e2e.cy.js
  packages/blocks/core/js/wordpress/columns/test/block-attributes.blocks.e2e.cy.js
  packages/blocks/core/js/wordpress/comments-pagination/test/block-attributes.blocks.e2e.cy.js
  packages/blocks/core/js/wordpress/gallery/test/block-attributes.blocks.e2e.cy.js
  packages/blocks/core/php/woocommerce/mini-cart-footer-block/block.php
  packages/blocks/core/php/woocommerce/product-template/block.php
  packages/blocks/core/php/wordpress/buttons/block.php
  packages/blocks/core/php/wordpress/columns/block.php
  packages/blocks/core/php/wordpress/comments-pagination/block.php
  packages/blocks/core/php/wordpress/gallery/block.php
  packages/blocks/core/php/wordpress/post-author/block.php
  packages/blocks/core/php/wordpress/query-pagination/block.php
  packages/blocks/core/php/wordpress/social-links/block.php
Labels: Bug

#255 Development: Playground demo improvements
  .github-playground.json
  .github-pr-playground.example.json
  .github/workflows/create-demo-attachments.yml
Labels: Enhancement

#257 Fix: Flaky tests
  .pr-cypress.env-example.json
  cypress.config.js
  packages/blocks/core/js/wordpress/home-link/test/block.blocks-home-link.e2e.cy.js
  packages/blocks/core/js/wordpress/navigation-link/test/functionality.blocks-navigation-link.e2e.cy.js
  packages/dev-cypress/js/plugins/index.js
Labels: Bug

#261 Blocksy Compatibility: Tests update
  packages/blocks/core/js/third-party/blocksy-about-me/test/about-me-block.blocksy.e2e.cy.js
  packages/blocks/core/js/third-party/blocksy-breadcrumbs/test/breadcrumbs-block.blocksy.e2e.cy.js
  packages/blocks/core/js/third-party/blocksy-contact-info/test/contact-info-block.blocksy.e2e.cy.js
  packages/blocks/core/js/third-party/blocksy-search/test/search-block.blocksy.e2e.cy.js
  packages/blocks/core/js/third-party/blocksy-share-box/test/share-box-block.blocksy.e2e.cy.js
  packages/blocks/core/js/third-party/blocksy-socials/test/socials-block.blocksy.e2e.cy.js
Labels: Enhancement

#260 Feat: Improve drag feature
  packages/controls/js/libs/box-position-control/components/side-item.js
  packages/controls/js/libs/box-spacing-control/components/margin/margin-all.js
  packages/controls/js/libs/box-spacing-control/components/margin/margin-bottom.js
  packages/controls/js/libs/box-spacing-control/components/margin/margin-horizontal.js
  packages/controls/js/libs/box-spacing-control/components/margin/margin-left.js
  packages/controls/js/libs/box-spacing-control/components/margin/margin-right.js
  packages/controls/js/libs/box-spacing-control/components/margin/margin-top.js
  packages/controls/js/libs/box-spacing-control/components/margin/margin-vertical.js
  packages/controls/js/libs/box-spacing-control/components/padding/padding-all.js
  packages/controls/js/libs/box-spacing-control/components/padding/padding-bottom.js
  packages/controls/js/libs/box-spacing-control/components/padding/padding-horizontal.js
  packages/controls/js/libs/box-spacing-control/components/padding/padding-left.js
  packages/controls/js/libs/box-spacing-control/components/padding/padding-right.js
  packages/controls/js/libs/box-spacing-control/components/padding/padding-top.js
  packages/controls/js/libs/box-spacing-control/components/padding/padding-vertical.js
  packages/controls/js/libs/input-control/components/input.scss
  packages/controls/js/libs/input-control/test/input-control.cy.js
  packages/dev-cypress/js/support/commands.js
  packages/editor/js/extensions/libs/position/test/box-position.e2e.cy.js
  packages/editor/js/extensions/libs/spacing/test/spacing.e2e.cy.js
  packages/utils/CHANGELOG.md
  packages/utils/js/use-drag-value/index.js
  packages/utils/js/use-drag-value/test/use-drag-value.spec.js
Labels: Enhancement

#262 Fix: Border Line feature design issue
  packages/controls/CHANGELOG.md
  packages/controls/js/libs/box-border-control/index.js
  packages/controls/js/libs/box-border-control/style.scss
Labels: Enhancement

#265 Feat: Text Wrap Feature
  packages/blocks/core/php/shared/attributes.php
  packages/editor/CHANGELOG.md
  packages/editor/js/extensions/libs/base/config/typography.js
  packages/editor/js/extensions/libs/shared/index.js
  packages/editor/js/extensions/libs/typography/extension.js
  packages/editor/js/extensions/libs/typography/styles.js
  packages/editor/js/extensions/libs/typography/type/typography-props.js
  packages/editor/js/schemas/block-supports/typography-block-supports-list.json
  packages/editor/php/StyleDefinitions/Typography.php
Labels: Enhancement
